import {
  Size,
  ChartConfig,
  ChartData,
  Dataset,
} from "react-native-chart-kit/dist/HelperTypes";

export const themeColors = {
  white: "#ffff",
  green: "#0BB299",
  newGreen:'#5db598',
  red: "#F15E34",
  newRed:'#eb4647',
  yellow: "#F5B526",
  disable:"#D3D3D3",
  blackLight:"#3F3F3F"
};

export const customColors = {
  Black: "#000000",
  White: "#FFFFFF",
  Keppel: "#0BB299",
  Jonquil: "#F5D13E",
  lemonMeringue: "#FEF2CD",
  lightCyan: "#CFEFEC",
  palePink: "#FED4D6",
  peterRiver:'#3498db'
};

export const en ={
  select_pair:'Select Pair',
  cot_retail:'COT and Retail sentiment',
  economic_data:'Economic Data',
  weekly_cot_data:'COT Weekly Data',
  upload_screenshot:'Upload Screenshot',
  other_trade_details:'Other Trade Details',
  notes:'Notes',
  add_trade_tags:'Add Trade Tags'
}

export const currencyArray = [
  "EUR",
  "JPY",
  "USD",
  "CHF",
  "AUD",
  "CAD",
  "NZD",
  "GBP",
  "ZAR",
  "BTC",
  "XAU",
  "RUB",
  "MXN",
];

export const currenyPair = [
  "BTCUSD",
  "EURUSD",
  "GBPUSD",
  "USDJPY",
  "GBPJPY",
  "USDCAD",
  "EURAUD",
  "EURJPY",
  "AUDCAD",
  "AUDJPY",
  "AUDNZD",
  "AUDUSD",
  "CADJPY",
  "EURCAD",
  "EURCHF",
  // 'EURCZK',
  "EURGBP",
  // 'EURHUF',
  // 'EURNOK',
  "EURNZD",
  // 'EURPLN',
  // 'EURSEK',
  // 'EURTRY',
  "GBPCAD",
  "GBPCHF",
  "NZDCAD",
  "NZDJPY",
  "NZDUSD",
  "USDCHF",
  // 'USDCZK',
  // 'USDHUF',
  'USDMXN',
  // 'USDNOK',
  // 'USDPLN',
  // 'USDSEK',
  // 'USDSGD',
  // 'USDTHB',
  // 'USDTRY',
  'USDZAR',
  "CHFJPY",
  "AUDCHF",
  "GBPNZD",
  "NZDCHF",
  'XAGUSD',
  "XAUUSD",
  "CADCHF",
  "GBPAUD",
  // 'SGDJPY',
  // 'GBPNOK',
  // 'EURZAR',
  // 'AUDSGD',
  // 'GBPSEK',
  // 'CHFSGD',
  // 'EURSGD',
  // 'GBPSGD',
  // 'XAUGBP',
  // 'NOKJPY',
  // 'ZARJPY',
  // 'GBPTRY',
  'USDRUB',
  // 'SEKJPY',
  // 'EURMXN',
  // 'XAUAUD',
  // 'XAUEUR',
  // 'XAUJPY',
  // 'XAUCHF',
  // 'GBPMXN',
  // 'XAGAUD',
  // 'NOKSEK',
  // 'XAGEUR',
  'XPTUSD',
  'XPDUSD',
  // 'USDCNH',
  // 'ETHUSD',
  'BRLUSD',
];
export const otherCurrencies = ['EURODOLLARS','EUROGBP','EUROJPY']

export const chartConfig: ChartConfig = {
  backgroundGradientFrom: "white",
  backgroundGradientFromOpacity: 1,
  backgroundGradientTo: "white",
  backgroundGradientToOpacity: 1,
  color: (opacity = 1) => `rgba(0, 0, 0, ${opacity})`,
  strokeWidth: 3, // optional, default 3
  barPercentage: 1,
  decimalPlaces: 0,
  propsForLabels: {
    fontFamily: "Roboto",
    fontWeight: "bold",
  },
};
